name: Scheduled GitHub Pages Redeploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Check and build Packages
        run: |
          # Xoá file Packages cũ nếu có
          rm -f Packages Packages.gz
          
          # Lọc bỏ .deb lỗi
          for f in *.deb; do
            echo "Checking $f ..."
            if ! dpkg-deb -I "$f" >/dev/null 2>&1; then
              echo "❌ Error in $f → removing"
              rm -rf "$f"
            else
              echo "✅ OK: $f"
            fi
          done
          
          # Build Packages + Packages.gz
          dpkg-scanpackages -m . /dev/null > Packages
          gzip -c9 Packages > Packages.gz

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
